---
name: Feature Branch Workflow / GitHub Actions

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: read

jobs:
  packer-checks:
    name: Packer Feature Branch Workflow Checks
    uses: eingram-homelab/reusable-workflows/.github/workflows/_flattened-packer-f-workflow-checks.yaml@main
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.head_ref || github.ref_name }}
