---
name: PR Workflow / Packer
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  packer-checks:
    name: Packer PR Workflow Checks
    uses: eingram-homelab/reusable-workflows/.github/workflows/_flattened-packer-pr-workflow-checks.yaml@main
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.head_ref || github.ref_name }}
    secrets:
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
