---
name: Release Workflow / Packer
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  packer-build:
    name: Packer Release Workflow
    uses: eingram-homelab/reusable-workflows/.github/workflows/_flattened-packer-release-workflow.yaml@main
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.head_ref || github.ref_name }}
      skip_build: false
    secrets:
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
